/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RegistroCliente;
import modelo.Cliente;

/**
 *
 * @author Administrador
 */
public class ActualizarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarCliente
     */
    public ActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleUserLabel = new java.awt.Label();
        clientRutField = new javax.swing.JTextField();
        btnBuscarRut = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        userNameLabel1 = new javax.swing.JLabel();
        clientNameField = new javax.swing.JTextField();
        userLastNamLabel = new javax.swing.JLabel();
        clientLastNamField = new javax.swing.JTextField();
        clientSecLastNamField = new javax.swing.JTextField();
        userSecLastNamLabel = new javax.swing.JLabel();
        userAreaLabel = new javax.swing.JLabel();
        btnActualizarCliente = new javax.swing.JButton();
        areaClienteTextField = new javax.swing.JTextField();
        volverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittleUserLabel.setAlignment(java.awt.Label.CENTER);
        tittleUserLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tittleUserLabel.setText("CLIENTES");

        clientRutField.setMaximumSize(new java.awt.Dimension(200, 25));
        clientRutField.setMinimumSize(new java.awt.Dimension(200, 25));
        clientRutField.setPreferredSize(new java.awt.Dimension(200, 25));
        clientRutField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientRutFieldFocusGained(evt);
            }
        });
        clientRutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRutFieldActionPerformed(evt);
            }
        });

        btnBuscarRut.setText("Buscar por Rut");
        btnBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutActionPerformed(evt);
            }
        });

        userNameLabel.setText("Nombre");

        userNameLabel1.setText("Nombre");

        clientNameField.setMaximumSize(new java.awt.Dimension(200, 25));
        clientNameField.setMinimumSize(new java.awt.Dimension(200, 25));
        clientNameField.setPreferredSize(new java.awt.Dimension(200, 25));
        clientNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientNameFieldFocusGained(evt);
            }
        });

        userLastNamLabel.setText("Apellido Paterno");

        clientLastNamField.setMaximumSize(new java.awt.Dimension(200, 25));
        clientLastNamField.setMinimumSize(new java.awt.Dimension(200, 25));
        clientLastNamField.setPreferredSize(new java.awt.Dimension(200, 25));
        clientLastNamField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientLastNamFieldFocusGained(evt);
            }
        });

        clientSecLastNamField.setMaximumSize(new java.awt.Dimension(200, 25));
        clientSecLastNamField.setMinimumSize(new java.awt.Dimension(200, 25));
        clientSecLastNamField.setPreferredSize(new java.awt.Dimension(200, 25));
        clientSecLastNamField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientSecLastNamFieldFocusGained(evt);
            }
        });

        userSecLastNamLabel.setText("Apellido Materno");

        userAreaLabel.setText("Area");

        btnActualizarCliente.setText("Actualizar");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });

        areaClienteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaClienteTextFieldFocusGained(evt);
            }
        });

        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLastNamLabel)
                    .addComponent(userSecLastNamLabel)
                    .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(areaClienteTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientRutField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientLastNamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(clientSecLastNamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(tittleUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(userNameLabel)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(tittleUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRut)
                    .addComponent(clientRutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLastNamLabel)
                    .addComponent(clientLastNamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSecLastNamLabel)
                    .addComponent(clientSecLastNamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAreaLabel)
                    .addComponent(areaClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(251, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientRutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientRutFieldActionPerformed

    private void clientRutFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientRutFieldFocusGained
        // TODO add your handling code here:
        clientRutField.setText("");
        
    }//GEN-LAST:event_clientRutFieldFocusGained

    private void clientNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientNameFieldFocusGained
        // TODO add your handling code here:
        clientNameField.setText("");
    }//GEN-LAST:event_clientNameFieldFocusGained

    private void clientLastNamFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientLastNamFieldFocusGained
        // TODO add your handling code here:
        clientLastNamField.setText("");
    }//GEN-LAST:event_clientLastNamFieldFocusGained

    private void areaClienteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaClienteTextFieldFocusGained
        // TODO add your handling code here:
        areaClienteTextField.setText("");
    }//GEN-LAST:event_areaClienteTextFieldFocusGained

    private void btnBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutActionPerformed
        // TODO add your handling code here:
        String rut, nombre, paterno, materno, area;
        
                
        rut = clientRutField.getText();
        Cliente c = new Cliente();
        
        RegistroCliente rc = new RegistroCliente();
        c = rc.buscarRut(rut);
        
        clientNameField.setText(c.getNombre());
        clientLastNamField.setText(c.getAppPaterno());
        clientSecLastNamField.setText(c.getAppMaterno());
        areaClienteTextField.setText(c.getArea());
        
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarRutActionPerformed

    private void clientSecLastNamFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientSecLastNamFieldFocusGained
        // TODO add your handling code here:
        clientSecLastNamField.setText("");
    }//GEN-LAST:event_clientSecLastNamFieldFocusGained

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        // TODO add your handling code here
        Cliente cliente = new Cliente();
        RegistroCliente rc = new RegistroCliente();
        
        cliente.setNombre(clientNameField.getText());
        cliente.setAppPaterno(clientLastNamField.getText());
        cliente.setAppMaterno(clientSecLastNamField.getText());
        cliente.setArea(areaClienteTextField.getText());
        cliente.setRutCliente(clientRutField.getText());
                
        rc.modificarCliente(cliente);
        
        
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        // TODO add your handling code here:
        MenuInicio Me = new MenuInicio();
        Me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaClienteTextField;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JTextField clientLastNamField;
    private javax.swing.JTextField clientNameField;
    private javax.swing.JTextField clientRutField;
    private javax.swing.JTextField clientSecLastNamField;
    private java.awt.Label tittleUserLabel;
    private javax.swing.JLabel userAreaLabel;
    private javax.swing.JLabel userLastNamLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JLabel userSecLastNamLabel;
    private javax.swing.JButton volverMenu;
    // End of variables declaration//GEN-END:variables
}
