/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.RegistroCliente;
import controlador.RegistroUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Usuario;

/**
 *
 * @author JP
 */
public class Auditoria extends javax.swing.JFrame {

    /**
     * Creates new form Auditoria
     */
    private RegistroUsuario regUser = new RegistroUsuario();
    
    private RegistroCliente regCliente = new RegistroCliente();
    
    
    
    
    public Auditoria() {
        initComponents();
        
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverMenu = new javax.swing.JButton();
        tittleInfo = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        rutClienteInforme = new javax.swing.JTextField();
        btnBuscarRut = new javax.swing.JButton();
        volverMenu1 = new javax.swing.JButton();

        volverMenu.setText("Volver");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittleInfo.setAlignment(java.awt.Label.CENTER);
        tittleInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tittleInfo.setText("INFORME DE REGISTROS");

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Ap_Paterno", "Ap_Materno", "Area", "Desayuno", "Almuerzo", "Cena", "Colación Fria", "Colación Noche"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        btnBuscar.setText("Mostrar todo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarRut.setText("Buscar por Rut");
        btnBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutActionPerformed(evt);
            }
        });

        volverMenu1.setText("Volver");
        volverMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tittleInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(rutClienteInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(volverMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tittleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutClienteInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String  rut, nombre, apellidoPaterno, apellidoMaterno, area;
        boolean  desayuno, almuerzo, cena, colacionFria, colacionNoche ;
        
        
        RegistroCliente regCliente = new RegistroCliente();
        DefaultTableModel modelo = (DefaultTableModel) tablaUsuario.getModel();
        

        
        modelo.setRowCount(0);
        
        List<Cliente> lista = regCliente.listarCliente();

        for (Cliente tmp : lista) {
                rut = tmp.getRutCliente();
                nombre = tmp.getNombre();
                apellidoPaterno = tmp.getAppPaterno();
                apellidoMaterno = tmp.getAppMaterno();
                area = tmp.getArea();
                desayuno = tmp.isDesayuno();
                almuerzo = tmp.isAlmuerzo();
                cena = tmp.isCena();
                colacionFria = tmp.isColacionFria();
                colacionNoche = tmp.isColacionNoche();

                
                modelo.addRow(new Object[]{rut, nombre, apellidoPaterno, apellidoMaterno, area, desayuno, almuerzo, cena, colacionFria, colacionNoche});
            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutActionPerformed
        // TODO add your handling code here:
        
        String  rut, nombre, apellidoPaterno, apellidoMaterno, area;
        boolean  desayuno, almuerzo, cena, colacionFria, colacionNoche ;
        
        
        RegistroCliente regCliente = new RegistroCliente();
        DefaultTableModel modelo = (DefaultTableModel) tablaUsuario.getModel();
        

        
        modelo.setRowCount(0);
        
        Cliente cliente = regCliente.auditoriaRut(rutClienteInforme.getText());

        
                rut = cliente.getRutCliente();
                nombre = cliente.getNombre();
                apellidoPaterno = cliente.getAppPaterno();
                apellidoMaterno = cliente.getAppMaterno();
                area = cliente.getArea();
                desayuno = cliente.isDesayuno();
                almuerzo = cliente.isAlmuerzo();
                cena = cliente.isCena();
                colacionFria = cliente.isColacionFria();
                colacionNoche = cliente.isColacionNoche();

                
                modelo.addRow(new Object[]{rut, nombre, apellidoPaterno, apellidoMaterno, area, desayuno, almuerzo, cena, colacionFria, colacionNoche});
            
    }//GEN-LAST:event_btnBuscarRutActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        // TODO add your handling code here:
        MenuInicio Me = new MenuInicio();
        Me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    private void volverMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenu1ActionPerformed
        // TODO add your handling code here:
        MenuInicio Me = new MenuInicio();
        Me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Auditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Auditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Auditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Auditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Auditoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rutClienteInforme;
    public javax.swing.JTable tablaUsuario;
    private java.awt.Label tittleInfo;
    private javax.swing.JButton volverMenu;
    private javax.swing.JButton volverMenu1;
    // End of variables declaration//GEN-END:variables
}
