/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RegistroUsuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Administrador
 */
public class RegUsuarioView extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuarios
     */
    public RegUsuarioView() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tittleUserLabel = new java.awt.Label();
        userLabel = new javax.swing.JLabel();
        userRutField = new javax.swing.JTextField();
        userRutLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        userLastNameField = new javax.swing.JTextField();
        userSecNameField = new javax.swing.JTextField();
        userLastNamLabel = new javax.swing.JLabel();
        userSecLastNamLabel = new javax.swing.JLabel();
        createUserButton = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        rolAsignadoText = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Usuarios");

        tittleUserLabel.setAlignment(java.awt.Label.CENTER);
        tittleUserLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tittleUserLabel.setText("USUARIOS");

        userLabel.setText("Ingrese los datos del Usuario");

        userRutField.setMaximumSize(new java.awt.Dimension(200, 25));
        userRutField.setMinimumSize(new java.awt.Dimension(200, 25));
        userRutField.setPreferredSize(new java.awt.Dimension(200, 25));
        userRutField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userRutFieldFocusGained(evt);
            }
        });

        userRutLabel.setText("Rut (12345678-4)");

        userNameLabel.setText("Nombre");

        userNameField.setMaximumSize(new java.awt.Dimension(200, 25));
        userNameField.setMinimumSize(new java.awt.Dimension(200, 25));
        userNameField.setPreferredSize(new java.awt.Dimension(200, 25));
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
        });

        userLastNameField.setMaximumSize(new java.awt.Dimension(200, 25));
        userLastNameField.setMinimumSize(new java.awt.Dimension(200, 25));
        userLastNameField.setPreferredSize(new java.awt.Dimension(200, 25));
        userLastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userLastNameFieldFocusGained(evt);
            }
        });

        userSecNameField.setMaximumSize(new java.awt.Dimension(200, 25));
        userSecNameField.setMinimumSize(new java.awt.Dimension(200, 25));
        userSecNameField.setPreferredSize(new java.awt.Dimension(200, 25));
        userSecNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userSecNameFieldFocusGained(evt);
            }
        });

        userLastNamLabel.setText("Apellido Paterno");

        userSecLastNamLabel.setText("Apellido Materno");

        createUserButton.setText("Crear");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        btnActualizarUsuario.setText("Actualizar");
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });

        Label1.setText("Rol Asignado");

        rolAsignadoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rolAsignadoTextFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(userLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userRutLabel)
                        .addComponent(userNameLabel)
                        .addComponent(userLastNamLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userSecLastNamLabel))
                        .addGap(7, 7, 7))
                    .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userRutField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userLastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userSecNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rolAsignadoText))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarUsuario)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userLabel)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userRutLabel)
                    .addComponent(userRutField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLastNamLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSecLastNamLabel)
                    .addComponent(userSecNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(rolAsignadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserButton)
                    .addComponent(btnActualizarUsuario))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        String rut, nombre, apellidoPaterno, apellidoMaterno, rolAsignado;
        
        
        rut = userRutField.getText();
        nombre = userNameField.getText();
        apellidoPaterno = userLastNameField.getText();
        apellidoMaterno = userSecNameField.getText();
        rolAsignado = rolAsignadoText.getText();
        
        
        Usuario newUser = new Usuario(0, rut, nombre, apellidoPaterno, apellidoMaterno, rolAsignado);
        RegistroUsuario regUser = new RegistroUsuario();
        
        regUser.crearUsuario(newUser);
        System.out.println("Usuario Agregado");

        
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void userRutFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userRutFieldFocusGained
        userRutField.setText("");
    }//GEN-LAST:event_userRutFieldFocusGained

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained
        userNameField.setText("");
    }//GEN-LAST:event_userNameFieldFocusGained

    private void userLastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userLastNameFieldFocusGained
        userLastNameField.setText("");
    }//GEN-LAST:event_userLastNameFieldFocusGained

    private void userSecNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userSecNameFieldFocusGained
        userSecNameField.setText("");
    }//GEN-LAST:event_userSecNameFieldFocusGained

    private void rolAsignadoTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rolAsignadoTextFocusGained
        rolAsignadoText.setText("");
    }//GEN-LAST:event_rolAsignadoTextFocusGained

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
                String rut, nombre, apellidoPaterno, apellidoMaterno, rolAsignado;
        
        
        rut = userRutField.getText();
        nombre = userNameField.getText();
        apellidoPaterno = userLastNameField.getText();
        apellidoMaterno = userSecNameField.getText();
        rolAsignado = rolAsignadoText.getText();
        
        
        Usuario newUser = new Usuario(0, rut, nombre, apellidoPaterno, apellidoMaterno, rolAsignado);
        RegistroUsuario regUser = new RegistroUsuario();
        
        regUser.actualizarUsuario(newUser);
        System.out.println("Usuario Actualizado");
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField rolAsignadoText;
    private java.awt.Label tittleUserLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLastNamLabel;
    private javax.swing.JTextField userLastNameField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userRutField;
    private javax.swing.JLabel userRutLabel;
    private javax.swing.JLabel userSecLastNamLabel;
    private javax.swing.JTextField userSecNameField;
    // End of variables declaration//GEN-END:variables
}
